### ISSUE TITLE
Gather data and decide if block-scoped functions should be redeclarable

### ISSUE THREAD

**Issue by syg** [tc39/ecma262#320] opened 2016-01-23 01:09 UTC
Firefox, Chrome, and Edge have all run into web-compat breakages regarding block-scope function redeclaration. Per ES2015, the following is an early error.

```javascript
{
  function f() { }
  function f() { }
}
```

Many existing sites, however, have variants of the above snippet and break. See the bugs for Firefox [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1235590), for Chrome [here](https://code.google.com/p/chromium/issues/detail?id=579395), and for Edge [here]( https://github.com/Microsoft/ChakraCore/issues/144).

It is my understanding the vendors here agree to back off on early errors for now and implement semantics described by Dave Herman [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1235590#c10), preferably with a deprecation warning visible in the console.

I would still like to see the early errors implemented, but it is clear there are major breakages and we need data to see if the spec needs changing.

FWIW, some prominent sites that have been broken have already rolled out fixes.

**Comment by bterlson** [comment] 2016-01-23 01:19
@syg can you expand on what sites are broken and which have been fixed? This will help with a gut-check for how widespread the issue is.

FWIW, https://github.com/Microsoft/ChakraCore/issues/144 is a bug against Chakra for not implementing the standard semantics. We actually haven't gotten around to fixing the bug yet and so don't have any compat experience to share yet :(

**Comment by syg** [comment] 2016-01-23 01:28
@bterlson For Firefox we saw Cisco Spark breakage, which reportedly has been fixed upstream already. The compat fix I landed in Firefox has telemetry probes, so once that hits Nightly we might get a better idea, though the Nightly population is small in comparison to release.

I think Chrome saw foxnews.com video player breakage. If V8's compat fix doesn't have telemetry in it I would certainly recommend they be added.

**Comment by concavelenz** [comment] 2016-01-23 01:52
I assume this is sloppy mode only?

**Comment by bterlson** [comment] 2016-01-23 03:22
Yes, sloppy only!

**Comment by allenwb** [comment] 2016-01-23 20:53
The reason this wasn't addressed in es6 the Annex B  was because snippets like this:
```js
{function f(){console.log("f1")}
 f();  // "f1" in SpiderMonkey, "f2" in most others
 function f(){console.log("f2")}
}
```
was not interoperable across browsers.

However, things like the following are interoperable but not covered by Annex B:

```js
{function f(){console.log("f1")}
 function f(){console.log("f2")}
 f();   //"f2" in all browsers
}

if (true) {
  function g(){console.log("g1")}
  function g(){console.log("g2")}
}
g();   //"g2" in all browsers
```
It seems to me that there is a fairly minimal addition to Annex B3.3 (sloppy mode) that can cover these cases:
 1. The 1st early error check in [14.1.2](https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-early-errors) for  *FunctionBody*:*FunctionStatementList* should not generate an early error for multiple function declarations using the same name. Instead it should treat it as a warning worthy condition.
 2. During BlockDeclarationInstantiation only the last occurring FunctionDeclaration for any name should be processed. Such  a final declaration is treated as if it was the sole declaration of that name in the block.  The other Annex B3.3 compatibility affordances also apply to the final declaration.

**Comment by littledan** [comment] 2016-01-25 04:41
We know of a couple: Not only Cisco WebEx, but also the Akamai Media Player (used by Fox News's website, for example). I'd guess that these come from the same underlying pattern of copying and pasting a function definition between files, and then having a "module system" concatenate multiple files together into the same sloppy-mode block-scoped region.

**Comment by syg** [comment] 2016-02-24 03:34
@bterlson @concavelenz I'm not sure this should be strict mode only. It should be Annex B.3.3 only, but those set of behaviors aren't limited to strict mode, right?

**Comment by syg** [comment] 2016-02-25 01:11
@littledan Proposed spec change [here](https://github.com/syg/ecma262/commit/3d6532fc413b1e0e649957ce90df0f6515ac237d) if you'd like to take a look.

**Closed** 2016-06-02 21:36 UTC
Labels: needs data
