### ISSUE TITLE
Sections which mix single-line and multi-line productions are hard to read

### ISSUE THREAD

**Issue by rkirsling** [tc39/ecma262#1639] opened 2019-07-20 22:13 UTC
Certain sections in the spec mix single-line productions in with multi-line productions, but since the two of these are indented differently, the output is extremely jarring. Taking [14.9.2.1](https://tc39.es/ecma262/#sec-statement-rules) for example:

![image](https://user-images.githubusercontent.com/2172590/61584618-a4379800-aaff-11e9-8da5-8a272163b313.png) 

Judging from the fact that single-line productions correspond to `<emu-production collapsed>`, my guess is that the difference in identation is intentional and the use of single-line productions in such sections is the bug. Thought I'd make an issue to confirm that before going ahead with a fix though.

(CC @bterlson)

**Comment by jmdyck** [comment] 2019-07-20 23:24
I'd say that the indentation of the multi-line productions is the bug.

In each (emu-grammar + emu-alg) group, the productions are the "head", so should have a smaller indent than the body.

**Comment by jmdyck** [comment] 2019-07-20 23:32
Duplicate of #956, I think.

**Comment by rkirsling** [comment] 2019-07-20 23:36
Thanks for that—I'd been assuming that the indentation of multi-line productions was intentional this whole time, just because it precedes my involvement. 😅

**Closed** 2020-01-03 06:46 UTC
