### ISSUE TITLE
optional type declaration for function parameter and return value like Python

### ISSUE THREAD

**Issue by lithic** [tc39/ecma262#1682] opened 2019-08-30 15:30 UTC

**Comment by ljharb** [comment] 2019-08-30 15:50
Please see https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal for how to best suggest new features for the language.

Duplicate of https://github.com/tc39/proposals/issues/239

**Closed by ljharb** 2019-08-30 15:50 UTC

**Comment by lithic** [comment] 2019-08-30 20:01
Are you a robot

**Comment by ljharb** [comment] 2019-08-30 23:13
Not that I’m aware.

**Comment by lithic** [comment] 2019-08-31 19:03
@ljharb please reopen this issue

**Comment by lithic** [comment] 2019-08-31 19:10
@ljharb there are many issues that are opened for discussion. please also make this one of them.

**Comment by lithic** [comment] 2019-08-31 19:11
@ljharb i am sorry for
>are you a robot

**Comment by nicolo-ribaudo** [comment] 2019-08-31 19:23
@lithic The issues opened for discussion are only for editorial changes to the spec text, or for really minor behavioral changes. New features, or big changes, require a separate proposal.

**Comment by ljharb** [comment] 2019-08-31 19:36
Specifically, no new features are discussed on this repo.
