### ISSUE TITLE
WhiteSpace/LineTerminator/LineTerminatorSequence definitions are not rendered properly

### ISSUE THREAD

**Issue by arai-a** [tc39/ecma262#1222] opened 2018-06-11 01:07 UTC
https://tc39.github.io/ecma262/#prod-WhiteSpace
```
WhiteSpace::
  <TAB> <VT> <FF> <SP> <NBSP> <ZWNBSP> <USP>
```

https://tc39.github.io/ecma262/#prod-LineTerminator
```
LineTerminator::
  <LF> <CR> <LS> <PS>
```

https://tc39.github.io/ecma262/#prod-LineTerminatorSequence
```
LineTerminatorSequence::
  <LF> <CR> [lookahead ≠ <LF> ]
  <LS> <PS> <CR> <LF>
```

items are not wrapped.
they make ECMAScript hard to write.

**Comment by gibson042** [comment] 2018-10-27 00:05
Duplicate of #1334; primary fix at https://github.com/rbuckton/grammarkdown/pull/29 .

**Comment by tzvipm** [comment] 2018-12-11 13:33
Now that rbuckton/grammarkdown#29 is merged, can we get a fix going for this?

**Comment by tzvipm** [comment] 2018-12-11 13:39
*Note*: I'd be happy to make a contribution for this, but I don't see where the underlying `.grammar` files are from `grammarkdown`.

**Comment by NilSet** [comment] 2018-12-27 02:36
I believe the proper fix requires a release of both grammarkdown and ecmarcup. For now I was able to locally confirm it is fixed on master of grammarkdown via `npm link`ing it into this project and rebuilding.

**Comment by NilSet** [comment] 2019-01-02 16:24
This is now fixed.

**Closed** 2019-01-02 17:55 UTC
Labels: rendering bug
