### ISSUE TITLE
.

### ISSUE THREAD

**Issue by anezdoank** [tc39/ecma262#2080] opened 2020-07-06 17:53 UTC
**Description:** Adding 1 and 1 is two, but it should be...

**eshost Output:**

```
$ eshost -s -e "1 + 1"
#### Chakra, JavaScriptCore, SpiderMonkey, V8, XS
2
```

**Comment by ljharb** [comment] 2020-07-06 18:26
Duplicate of #2079.

**Closed by ljharb** 2020-07-06 18:26 UTC
