### ISSUE TITLE
HasCallInTailPosition incorrectly checks 'for-await-of' instead of `for-of`

### ISSUE THREAD

**Issue by rbuckton** [tc39/ecma262#2544] opened 2021-10-07 00:52 UTC
In the syntax-directed operation [HasCallInTailPosition](https://tc39.es/ecma262/#sec-static-semantics-hascallintailposition) we have the following branch:

```grammarkdown
ForInOfStatement :
  `for` `(` LeftHandSideExpression `in` Expression `)` Statement
  `for` `(` `var` ForBinding `in` Expression `)` Statement
  `for` `(` ForDeclaration `in` Expression `)` Statement
  `for` `await` `(` LeftHandSideExpression `of` AssignmentExpression `)` Statement
  `for` `await` `(` `var` ForBinding `of` AssignmentExpression `)` Statement
  `for` `await` `(` ForDeclaration `of` AssignmentExpression `)` Statement
```

I believe this is in error. The grammar should be the following instead:

```grammarkdown
ForInOfStatement :
  `for` `(` LeftHandSideExpression `in` Expression `)` Statement
  `for` `(` `var` ForBinding `in` Expression `)` Statement
  `for` `(` ForDeclaration `in` Expression `)` Statement
  `for` `(` LeftHandSideExpression `of` AssignmentExpression `)` Statement
  `for` `(` `var` ForBinding `of` AssignmentExpression `)` Statement
  `for` `(` ForDeclaration `of` AssignmentExpression `)` Statement
```

As it stands, this branch does not correctly handle `for-of` (as it only includes `for-await-of`), and HasCallInTailPosition won't be called in a `[+Await]` context given that _AsyncFunctionBody_, _AsyncGeneratorFunctionBody_, and _AsyncConciseBody_ are excluded by [IsInTailPosition](https://tc39.es/ecma262/#sec-isintailposition) (steps 5, 6, and 7), which is the only caller to HasCallInTailPosition (other than HasCallInTailPosition itself).

**Comment by bakkot** [comment] 2021-10-07 01:32
I believe this is a duplicate of https://github.com/tc39/ecma262/issues/2279, which I completely forgot to address. Closing as a duplicate of that issue, but thanks for raising it again; I'll try to get it addressed.

(My understanding is that it shouldn't recurse into for-of, because for-of loops have logic to close the iterator which runs after call in the `return` is evaluated - see [ForIn/OfBodyEvaluation](https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-runtime-semantics-forin-div-ofbodyevaluation-lhs-stmt-iterator-lhskind-labelset) step 6.k.iv.2. And indeed HasCallInTailPosition does explicitly `Return false.` for for-of loops.)

**Closed by bakkot** 2021-10-07 01:32 UTC
