### ISSUE TITLE
LineTerminator Grammar misformatted start with ES2018

### ISSUE THREAD

**Issue by allenwb** [tc39/ecma262#1336] opened 2018-10-26 22:12 UTC
Starting with the ES2018 version of ECMA-262 the BNF for _LineTerminator_ is incorrectly formatted (or rendered) in a manner that makes its definition incorrect.

In [ES18](https://ecma-international.org/ecma-262/9.0/index.html#sec-line-terminators) and the current working drafts it looks like this:

![lineterm2018](https://user-images.githubusercontent.com/505435/47594523-8e11f800-d930-11e8-9d82-f61c511860e1.jpg)

In [ES2017](https://ecma-international.org/ecma-262/8.0/index.html#sec-line-terminators) and prior editions it correctly looks like this:
![linrterm2017](https://user-images.githubusercontent.com/505435/47594681-55265300-d931-11e8-99ad-37e7e731dd68.jpg)

**Comment by loganfsmyth** [comment] 2018-10-26 22:14
I also noticed this recently, but it's already filed as https://github.com/tc39/ecma262/issues/1222

**Comment by gibson042** [comment] 2018-10-27 00:05
Duplicate of #1334; primary fix at https://github.com/rbuckton/grammarkdown/pull/29 (cc @rbuckton).

**Comment by NilSet** [comment] 2019-01-02 16:24
This is now fixed.

**Comment by ljharb** [comment] 2019-01-02 17:54
Fixed by https://github.com/rbuckton/grammarkdown/pull/29 / #1381

**Closed by ljharb** 2019-01-02 17:54 UTC
Labels: rendering bug
