### ISSUE TITLE
bitlength of Bigint

### ISSUE THREAD

**Issue by ppKrauss** [tc39/ecma262#1729] opened 2019-10-08 16:06 UTC
As [commented here](https://stackoverflow.com/q/54758130/287948), in nowadays there are no alternative to the **worst case**: 

     let  numberOfBitsInX = x.toString(2).length

There are a discussion or "official rationale" about access to the number of bits used by a BigInt value?  

Ideal is to offer an internal native method for bitLength of BigInt...  At this moment BigInt is on "Stage 4", how to include this feature to the definitive standard of BigInt?
 
PS: BigInt is not a fixed-length data type, must  offer *.length*, *.size*  or *.bitLength*  property.

**Comment by ljharb** [comment] 2019-10-08 16:21
See https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal which describes the paths forward for that suggestion.

**Comment by devsnek** [comment] 2019-10-08 16:24
Also food for thought: If `Math` functions worked on bigints, you could use `Math.log2(n) + 1n`.

**Comment by ppKrauss** [comment] 2019-10-08 17:14
@devsnek , 

> Also food for thought: If `Math` functions worked on bigints, you could use `Math.log2(n) + 1n`.

A good *log2(n)* implementation is fast,  but performance depends on the `n` length. The 
 access the number of bytes or blocks in the BigInt internal representation will be faster... No sense hiding this information, many applications demand bitlength information to be also fast and practicable.

------

@ljharb ,
> 
> See https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal which describes the paths forward for that suggestion.

My question is also about **"is this gap in the BigInt standard a new-proposal?"** Seems a bug to be corrected before to 2020 release (!).

**Comment by ljharb** [comment] 2019-10-08 17:23
It’s not a bug; it’s an intentional omission/deferral to a future proposal. See https://github.com/tc39/proposal-bigint/issues/205

**Comment by ppKrauss** [comment] 2019-10-08 19:08
Hi @ljharb, I [commented there adding a consistent algorithm](https://github.com/tc39/proposal-bigint/issues/205#issuecomment-539652380) ... It is time to propose something.  Can you help me to "introduce to the committee" a new proposal?  I am not in the [esdiscuss](https://esdiscuss.org/), neither speak English, but can build first draft of the [documents](https://tc39.es/process-document/), co-authoring with you or somebody else.

Important to say to committee that is not an "isolated new proposal", but a small patch for the BigInt proposal.

**Comment by ljharb** [comment] 2019-10-08 19:28
Please follow the suggestions here: https://github.com/tc39/ecma262/blob/master/CONTRIBUTING.md#creating-a-new-proposal

I’m going to close this, since the question is answerved, and feature suggestions aren’t meant to be discussed in this repo.

**Closed by ljharb** 2019-10-08 19:28 UTC
