### ISSUE TITLE
Editorial: more obvious syntax for macros

### ISSUE THREAD

**Issue by bakkot** [tc39/ecma262#2384] opened 2021-04-13 01:24 UTC
Macros like [ReturnIfAbrupt](https://tc39.es/ecma262/#sec-returnifabrupt) and [IfAbruptRejectPromise](https://tc39.es/ecma262/#sec-ifabruptrejectpromise) are called like AOs, but they can have effects on the control flow and aliases in caller, which is [confusing](https://github.com/tc39/ecma262/issues/2178#issuecomment-818338069).

We should make it more obvious at the callsites that these are not normal AOs.

(I don't think this extends to the `?` and `!` macros, since uses of those symbols do not look like a normal AO invocation.)

**Comment by ljharb** [comment] 2021-04-13 01:26
Perhaps we could find all non-symbolic uses of `ReturnIfAbrupt`, and find a way to replace it with `?`/`!`?

Then, perhaps we could come up with a symbolic form of `IfAbruptRejectPromise`?

**Comment by bakkot** [comment] 2021-04-13 01:30
> Then, perhaps we could come up with a symbolic form of `IfAbruptRejectPromise`?

And [`IfAbruptCloseIterator`](https://github.com/tc39/ecma262/pull/2113), presumably? I think it's probably better to have some way of marking macros in general, rather than trying to invent unique syntax for each one.

**Comment by jmdyck** [comment] 2021-04-13 03:30
Shorthands that are invoked like abstract ops:
- ReturnIfAbrupt
- Await
- IfAbruptRejectPromise
- NormalCompletion
- ThrowCompletion

However, I think NormalCompletion and ThrowCompletion could be defined as regular abstract ops.

**Comment by ljharb** [comment] 2021-04-13 03:32
Both already are, no?

**Comment by jmdyck** [comment] 2021-04-13 03:36
Well, they *say* they're abstract operations, but they're *defined* as shorthands, so they're weird.

**Comment by ExE-Boss** [comment] 2022-02-28 17:31
We could probably prefix their names with a `%` sign, which is what assembly languages generally do, and it’s probably more visible than suffixing them with an `!` without any other syntax highlighting, e.g.:
- <code>[%ReturnIfAbrupt]\(<var>argument</var>)</code>
- <code>[%IfAbruptRejectPromise]\(<var>value</var>, <var>promiseCapability</var>)</code>
- <code>[%IfAbruptCloseIterator]\(<var>value</var>, <var>iteratorRecord</var>)</code>

[%ReturnIfAbrupt]: https://tc39.es/ecma262/#sec-returnifabrupt
[%IfAbruptRejectPromise]: https://tc39.es/ecma262/#sec-ifabruptrejectpromise
[%IfAbruptCloseIterator]: https://tc39.es/ecma262/#sec-ifabruptcloseiterator

This would also solve <https://github.com/tc39/ecma262/issues/2498>.

**Comment by michaelficarra** [comment] 2022-06-29 16:59
Closing as duplicate of #2498.

**Closed by michaelficarra** 2022-06-29 16:59 UTC
