### ISSUE TITLE
Elladamalikova@hotmail.com

### ISSUE THREAD

**Issue by saimakin** [tc39/ecma262#2100] opened 2020-07-19 04:17 UTC
**Description:** Adding 1 and 1 is two, but it should be...

**eshost Output:**

```
$ eshost -s -e "1 + 1"
#### Chakra, JavaScriptCore, SpiderMonkey, V8, XS
2
```

**Comment by saimakin** [comment] 2020-07-19 04:17
Elladamalikova@hotmail.com

**Comment by ljharb** [comment] 2020-07-19 04:56
Duplicate of #2080. Duplicate of #2079.

Also, spam.

**Closed by ljharb** 2020-07-19 04:56 UTC
