### ISSUE TITLE
Canonicalize AO (and possibly other RegExp AOs) have implicit parameters

### ISSUE THREAD

**Issue by michaelficarra** [tc39/ecma262#2480] opened 2021-08-04 22:12 UTC
https://tc39.es/ecma262/#sec-runtime-semantics-canonicalize-ch

This AO refers to a `Unicode` parameter that doesn't exist.

**Comment by bakkot** [comment] 2021-08-04 22:22
Closing as a duplicate of #1884.

**Closed by bakkot** 2021-08-04 22:22 UTC
Labels: editor call
