### ISSUE TITLE
B.1.4 AtomEscape production syntax incomplete

### ISSUE THREAD

**Issue by hashseed** [tc39/ecma262#378] opened 2016-02-10 09:30 UTC
In http://tc39.github.io/ecma262/#sec-regular-expressions-patterns

AtomEscape[U] ::
  [+U] DecimalEscape
  [+U] CharacterEscape[U]
  [+U] CharacterClassEscape
  [~U] DecimalEscape only if the integer value
  [~U] CharacterClassEscape
  [~U] CharacterEscape

It should be

AtomEscape[U] ::
  [+U] DecimalEscape
  [+U] CharacterEscape[U]
  [+U] CharacterClassEscape
  [~U] DecimalEscape but only if the integer value of DecimalEscape is <= NCapturingParens
  [~U] CharacterClassEscape
  [~U] CharacterEscape

The condition for ~U is necessary so that we can fall back to CharacterEscape, which may interpret the digits as legacy octal escape.

**Comment by michaelficarra** [comment] 2016-02-10 13:44
This seems to be another duplicate of #363, #358,  #325.

**Comment by bterlson** [comment] 2016-02-17 23:47
Indeed, same issue.

**Closed** 2016-02-17 23:49 UTC
