### ISSUE TITLE
Section 23 does not expand when clicked.

### ISSUE THREAD

**Issue by ursi** [tc39/ecma262#1789] opened 2019-11-20 23:33 UTC
this is with the version hosted at https://tc39.es/ecma262
**Doesn't Work:** Brave 1.1.1
**Doesn't Work:** Chrome 78.0.3904
**Works:** Firefox 70.0.1

**Comment by ljharb** [comment] 2019-11-20 23:38
Works in Safari as well, and only that section seems to not expand in Chrome.

**Comment by jmdyck** [comment] 2019-11-22 01:20
I tried it in Chrome 75.0.3770, worked for me.

**Comment by bakkot** [comment] 2019-11-22 02:56
The issue I observe is that scrolling to section 23 (either manually, by clicking the link in the sidebar, or by clicking a link such as [this one](https://tc39.es/ecma262/#sec-keyed-collections)) does not cause that section to expand in the sidebar.

I expect this is because that section has `oldids="sec-keyed-collection"`, which causes a `<span id="sec-keyed-collection"></span>` tag to be inserted at the beginning of the section. Ecmarkup [relies on the `margin-top` of the first child of a clause](https://github.com/bterlson/ecmarkup/blob/a631c87575f3fab1a22d0b79c76abdbcebc4f0e9/js/menu.js#L342-L343) as a part of figuring out which clause you are within. Normally that's the `<h1>` containing the section name, which has a fairly large margin, but here it's the `<span>`, which has no margin at all. Since clicking on the anchor puts you very slightly above the clause element (a fraction of a pixel, in my browsers), ecmarkup does not recognize you as being within the clause.

That said, I observe this in Firefox and Safari as well as Chrome, so maybe that's not the issue described here. @ljharb or @Ursi, can you describe the issue you see more precisely?

**Comment by Ursi** [comment] 2019-11-22 03:23
@bakkot I'm not at all familiar with the code that makes up the spec. Is there anything in particular you want?

**Comment by bakkot** [comment] 2019-11-22 03:28
@Ursi I am interested in what bugged behavior you observe. Is it that clicking on "23 Keyed Collections" in the sidebar scrolls you to that section but does not expand it in the sidebar? If so, do you observe that scrolling the main page down slightly does cause it to expand in the sidebar?

**Comment by Ursi** [comment] 2019-11-22 03:43
@bakkot when click I am scrolled to the section, however the section is not expanded on the sidebar. If I scroll down by even a pixel (`document.scrollingElement.scrollTop++`) it will expand.

**Comment by rkirsling** [comment] 2019-11-22 03:45
I can confirm that deleting the `<span>` or removing `oldids` and rebuilding fixes the issue.
(Explicit `height: 0;` or `visibility: hidden;` or even `display: none;` doesn't help.)

FWIW, in addition to the originally-suggested results, I also repro this in STP 96.

**Comment by ljharb** [comment] 2019-11-22 04:10
Seems like "relies on the margin-top of the first child of a clause" in ecmarkup is the brittle piece; can that be made more robust?

**Comment by bakkot** [comment] 2020-05-08 00:50
Reopening this until ecmarkup is upstreamed.

**Comment by bakkot** [comment] 2020-05-20 21:49
This is fixed now that ecmarkup has been upstreamed in https://github.com/tc39/ecma262/pull/1995.

**Closed by bakkot** 2020-05-20 21:49 UTC
Labels: rendering bug
